
export const findCurrency = (currency: string): string => {
  const currencyMap: Record<string, string> = {
    'USD': '$',
    'EUR': '€',
    'GBP': '£',
    'INR': '₹',
    'JPY': '¥',
    'AUD': 'A$',
    'CAD': 'C$',
    'CNY': '¥',
    'RUB': '₽',
    'BRL': 'R$',
    'ZAR': 'R',
    'KRW': '₩',
    'MXN': '$',
    'NZD': 'NZ$',
    'SGD': 'S$',
    'HKD': 'HK$',
    'SEK': 'kr',
    'NOK': 'kr',
    'DKK': 'kr',
    'PLN': 'zł',
    'TRY': '₺',
    'TWD': 'NT$',
    'THB': '฿',
    'IDR': 'Rp',
    'MYR': 'RM',
    'PHP': '₱',
    'VND': '₫',
    'AED': 'د.إ',
    'SAR': 'ر.س',
    'QAR': 'ر.ق',
    'KWD': 'د.ك',
    'OMR': 'ر.ع.',
    'BHD': 'د.ب',
    'JOD': 'د.أ',
    'EGP': 'ج.م',
    'MAD': 'د.م.',
    'ARS': '$',
    'CLP': '$',
    'COP': '$',
    'PEN': 'S/',
    'UYU': '$U',
    'CRC': '₡',
    'GTQ': 'Q',
    'HNL': 'L',
    'NIO': 'C$',
    'SVC': '$',
    'PYG': '₲',
    'BOB': 'Bs',
    'VEF': 'Bs',
    'DOP': 'RD$',
    'CUP': '₱',
    'CUC': '$',
    'XAF': 'FCFA',
    'XOF': 'CFA',
  };
  
  return currencyMap[currency] || currency; // Fallback to the currency code if not found
}